spring.application.name=cloudtestapp

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:8889/cloud_test_app
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true